name: Release Drafter
on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        with:
          config-name: release-drafter-config.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: test
        run: |
          npm version ${{ steps.release-drafter.outputs.tag_name }}
          git push origin master