on:
  release:
    types: [published]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get Tag Name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - uses: fregante/setup-git-user@v1
      - name: test
        run: |
          git tag -d ${{ steps.tag_name.outputs.SOURCE_TAG }}
          npm version ${{ steps.tag_name.outputs.SOURCE_TAG }}
          git push origin master