name: Version Check
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  auto-bumping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: version check
        run: BRANCH_NAME=$HEAD_BRANCH node ./tools/version-check.js
        env:
          HEAD_BRANCH: ${{ github.head_ref }}